"""I think i fixed the file reference stuff

Revision ID: 19ef9d9564ff
Revises: ff6252d81d73
Create Date: 2023-08-24 13:53:09.793117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19ef9d9564ff'
down_revision = 'ff6252d81d73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'file_reference')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('file_reference', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
