"""Added release and file models

Revision ID: 1f2b5b1da21b
Revises: 
Create Date: 2023-08-23 20:00:57.682571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f2b5b1da21b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('release',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('song_title', sa.String(length=200), nullable=False),
    sa.Column('artist_name', sa.String(length=200), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=False),
    sa.Column('label_copy_text', sa.Text(), nullable=True),
    sa.Column('release_instructions', sa.Text(), nullable=True),
    sa.Column('is_album', sa.Boolean(), nullable=True),
    sa.Column('album_order', sa.Integer(), nullable=True),
    sa.Column('algo_support_acknowledged', sa.Boolean(), nullable=True),
    sa.Column('rush_fee_approved', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('release_id', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('file_reference', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['release_id'], ['release.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('isrc')
    op.drop_table('upc')
    op.drop_table('song')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('song',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('song_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('song_title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('artist_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('release_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('genre', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('sub_genre', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('song_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='song_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('upc',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('upc_code', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('song_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], name='upc_song_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='upc_pkey')
    )
    op.create_table('isrc',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('isrc_code', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('song_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], name='isrc_song_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='isrc_pkey')
    )
    op.drop_table('file')
    op.drop_table('release')
    # ### end Alembic commands ###
