"""Removed album_order from Release

Revision ID: 283fba601543
Revises: 1f2b5b1da21b
Create Date: 2023-08-23 20:28:30.424110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '283fba601543'
down_revision = '1f2b5b1da21b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('release', 'album_order')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('release', sa.Column('album_order', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
