"""Added direct to GCS

Revision ID: 8a372e8d7c24
Revises: 283fba601543
Create Date: 2023-08-24 10:10:53.454833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a372e8d7c24'
down_revision = '283fba601543'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('gcs_path', sa.String(length=500), nullable=True))
    op.execute("UPDATE file SET gcs_path='default_value'")  # Replace 'default_value' with an appropriate default if you have one.
    op.alter_column('file', 'gcs_path', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'gcs_path')
    # ### end Alembic commands ###
