"""Added some tings

Revision ID: ff6252d81d73
Revises: 8a372e8d7c24
Create Date: 2023-08-24 13:38:38.406869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff6252d81d73'
down_revision = '8a372e8d7c24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('release', sa.Column('created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('release', 'created')
    # ### end Alembic commands ###
